'use client';
import {useState,useEffect} from 'react';
import {Info,TrendingUp,CalendarDays} from 'lucide-react';
import {Select,Table} from '@reef/ui';
import type {Dashboard,Historical} from '@reef/types';
import {useResource} from '@/lib/hooks';
import {shortDate,number,money} from '@/lib/format';
import {PageTitle,Panel,Loading,ErrorState,SourceBadge,StatusBadge} from '@/components/shared';
import {BookingChart} from '@/components/booking-chart';
import {SalesEntry} from '@/components/sales-entry';
export default function TicketsPage(){
 const {data:d,error,loading,refresh}=useResource<Dashboard>('/dashboard');const {data:history}=useResource<{rows:Historical[]}>('/history');const [selected,setSelected]=useState('resolution-2027-02-02'),[compare,setCompare]=useState('');
 useEffect(()=>{const p=new URLSearchParams(window.location.search).get('screening');if(p)setSelected(p);},[]);
 if(loading)return <Loading/>;if(error||!d)return <ErrorState message={error} retry={refresh}/>;const s=d.screenings.find(x=>x.id===selected)??d.screenings[0];
 const historyGroups=[...new Map((history?.rows??[]).map(r=>[r.source_url,`${r.programme} · ${shortDate(r.show_date)}`])).entries()];
 return <><PageTitle eyebrow="TICKET SALES" title="Every Tuesday has its own curve" description="Compare observed sales with the management target, then focus on the gap." action={<SalesEntry screenings={d.screenings} onSaved={refresh}/>}/><div className="toolbar"><div className="tabs" role="tablist" aria-label="Screenings">{d.screenings.map(x=><button role="tab" aria-selected={s.id===x.id} className="tab" key={x.id} onClick={()=>setSelected(x.id)}>{shortDate(x.date)}</button>)}</div><span className="microcopy">{s.days_until} days until screening · {s.time??'Time to be confirmed'}</span></div>
 <div className="split-layout"><Panel title={`${shortDate(s.date)} · Booking performance`} aside={<StatusBadge status={s.decision.status}/>}><div style={{height:310}}><BookingChart curve={d.curve} actual={s.actual_curve} history={(history?.rows??[]).filter(r=>r.source_url===compare)}/></div><div className="legend"><span><i/>Management target</span><span><i className="actual"/>Resolution observations</span>{compare&&<span>Archived ESO inventory (not confirmed sales)</span>}</div><div className="field section-gap"><label className="label" htmlFor="compare">Compare an archived ESO booking curve</label><Select id="compare" value={compare} onChange={e=>setCompare(e.target.value)}><option value="">Resolution only</option>{historyGroups.map(([url,label])=><option key={url} value={url}>{label}</option>)}</Select></div><p className="microcopy">Historical points come from archived ESO inventory on 23–24 September 2026. Unavailable seats may include holds. These curves do not establish final attendance or marketing lift.</p></Panel>
 <Panel title="Expected final ticket sales" aside={<SourceBadge source="ESTIMATED"/>}><div className="forecast-range">{(['low','base','high'] as const).map(k=><div key={k}><span>{k.toUpperCase()}</span><strong>{number(s.forecast[k])}</strong></div>)}</div><p className="microcopy">{s.forecast.confidence_note}</p><div className="section-gap">{[['Observed tickets',number(s.tickets_sold)],['Seats remaining',number(s.seats_remaining)],['Target by today',number(s.decision.target_today)],['Sales needed today',number(s.forecast.gap_to_target)],['3-day velocity',`${number(s.velocity_3)} / day`],['7-day velocity',`${number(s.velocity_7)} / day`],['Required pace to final target',`${number(s.forecast.required_sales_pace)} / day`]].map(([k,v])=><div className="data-detail" key={k}><span>{k}</span><strong>{v}</strong></div>)}</div></Panel></div>
 <div className="notice section-gap"><Info size={18}/><span>{s.decision.action} Recommended budget: <strong>{money(s.decision.recommended_budget_cents)}</strong>. {s.stale?'The latest observation is stale.':''}</span></div>
 <Panel title="All screenings at a glance"><Table><thead><tr><th>Screening</th><th>Observed</th><th>Target</th><th>Gap</th><th>3-day pace</th><th>7-day pace</th><th>Final estimate</th><th>Status</th><th>Source</th></tr></thead><tbody>{d.screenings.map(r=><tr key={r.id}><td>{shortDate(r.date)}<small>{r.time??'Time TBC'}</small></td><td>{number(r.tickets_sold)} / {r.capacity}</td><td>{r.decision.target_today}</td><td>{number(r.forecast.gap_to_target)}</td><td>{number(r.velocity_3)}</td><td>{number(r.velocity_7)}</td><td>{r.forecast.base===null?'Awaiting data':`${r.forecast.low} / ${r.forecast.base} / ${r.forecast.high}`}</td><td><StatusBadge status={r.decision.status}/></td><td><SourceBadge source={r.source_label}/></td></tr>)}</tbody></Table></Panel>
 <div className="two-columns section-gap"><Panel title="Management milestones" aside={<SourceBadge source="PLANNING ASSUMPTION"/>}><Table><thead><tr><th>Before screening</th><th>Target tickets</th><th>Occupancy</th></tr></thead><tbody>{d.curve.map(p=><tr key={p.days}><td>{p.days===0?'Show day':`${p.days} days`}</td><td>{p.tickets} / 109</td><td>{Math.round(p.tickets/109*100)}%</td></tr>)}</tbody></Table></Panel><Panel title="Observation history"><Table><thead><tr><th>Observed</th><th>Tickets</th><th>Days before</th></tr></thead><tbody>{s.actual_curve.length?s.actual_curve.toReversed().map(p=><tr key={p.observed_at}><td>{new Date(p.observed_at).toLocaleString('en-GB',{timeZone:'Europe/Berlin'})}</td><td>{p.tickets}</td><td>{p.days}</td></tr>):<tr><td colSpan={3}>No Resolution ticket observations yet.</td></tr>}</tbody></Table><p className="microcopy section-gap">Save the cumulative count each day. Three- and seven-day pace appear once a full observation window exists.</p></Panel></div></>;
}
