'use client';
import {useState,useEffect} from 'react';
import {Info,TrendingUp,CalendarDays,Target,Activity} from 'lucide-react';
import {Select,Table} from '@reef/ui';
import type {Dashboard,Historical} from '@reef/types';
import {useResource} from '@/lib/hooks';
import {shortDate,number,money,percent} from '@/lib/format';
import {PageTitle,Panel,Loading,ErrorState,SourceBadge,StatusBadge,Metric} from '@/components/shared';
import {BookingChart} from '@/components/booking-chart';
import {SalesEntry} from '@/components/sales-entry';
export default function TicketsPage(){
 const {data:d,error,loading,refresh}=useResource<Dashboard>('/dashboard');const {data:history}=useResource<{rows:Historical[]}>('/history');const [selected,setSelected]=useState('resolution-2027-02-02'),[compare,setCompare]=useState('');
 useEffect(()=>{const p=new URLSearchParams(window.location.search).get('screening');if(p)setSelected(p);},[]);
 if(loading)return <Loading/>;if(error||!d)return <ErrorState message={error} retry={refresh}/>;const s=d.screenings.find(x=>x.id===selected)??d.screenings[0];const intel=d.sales_intelligence.screenings.find(x=>x.screening_id===s.id);const portfolio=d.sales_intelligence.portfolio;
 const historyGroups=[...new Map((history?.rows??[]).map(r=>[r.source_url,`${r.programme} · ${shortDate(r.show_date)}`])).entries()];
 return <><PageTitle eyebrow="SALES INTELLIGENCE" title="Forecast the finish, not just today" description="Track live booking pace, the next 7/14 days and expected final attendance for every screening." action={<SalesEntry screenings={d.screenings} onSaved={refresh}/>}/>
 <div className="kpi-grid"><Metric label="Expected final tickets" value={number(portfolio.final_base)} detail={`${number(portfolio.final_low)}–${number(portfolio.final_high)} planning range`} icon={<Target/>}/><Metric label="Portfolio occupancy" value={percent(portfolio.final_occupancy_pct)} detail={`${number(portfolio.capacity)} total seats`} icon={<Activity/>}/><Metric label="Expected new tickets · 7d" value={`+${number(portfolio.expected_new_tickets_7d)}`} detail="Modelled across all six screenings" icon={<TrendingUp/>}/><Metric label="Screenings below target" value={number(portfolio.screenings_below_target)} detail="Based on the configured attendance target" icon={<CalendarDays/>}/></div>
 <div className="toolbar"><div className="tabs" role="tablist" aria-label="Screenings">{d.screenings.map(x=><button role="tab" aria-selected={s.id===x.id} className="tab" key={x.id} onClick={()=>setSelected(x.id)}>{shortDate(x.date)}</button>)}</div><span className="microcopy">{s.days_until} days until screening · {s.time??'Time to be confirmed'}</span></div>
 <div className="split-layout"><Panel title={`${shortDate(s.date)} · Booking + forecast trajectory`} aside={<SourceBadge source={intel?.classification??'MODEL ESTIMATE'}/>}><div style={{height:310}}><BookingChart curve={d.curve} actual={s.actual_curve} history={(history?.rows??[]).filter(r=>r.source_url===compare)} forecast={intel?.trajectory??[]} capacity={s.capacity}/></div><div className="legend"><span><i/>Management target</span><span><i className="actual"/>Resolution observations</span><span>Forecast trajectory</span>{compare&&<span>Archived ESO inventory</span>}</div><div className="field section-gap"><label className="label" htmlFor="compare">Compare an archived ESO booking curve</label><Select id="compare" value={compare} onChange={e=>setCompare(e.target.value)}><option value="">Resolution only</option>{historyGroups.map(([url,label])=><option key={url} value={url}>{label}</option>)}</Select></div><p className="microcopy">Historical points are archived ESO inventory, not verified final attendance. Forecast trajectory is a model estimate and updates when Resolution observations are added.</p></Panel>
 <Panel title="What the model expects next" aside={<SourceBadge source="MODEL ESTIMATE"/>}><div className="forecast-range">{(['low','base','high'] as const).map(k=><div key={k}><span>{k.toUpperCase()}</span><strong>{number(s.forecast[k])}</strong></div>)}</div><p className="microcopy">{s.forecast.confidence_note}</p><div className="section-gap">{[['Expected new tickets · next 7d',intel?`+${number(intel.expected_new_tickets_7d)}`:'—'],['Expected cumulative · 7d',number(intel?.expected_cumulative_7d)],['Expected new tickets · next 14d',intel?`+${number(intel.expected_new_tickets_14d)}`:'—'],['Expected cumulative · 14d',number(intel?.expected_cumulative_14d)],['Final occupancy',percent(intel?.final_occupancy_pct)],['Forecast shortfall to target',number(intel?.forecast_shortfall)],['Sales pace trend',intel?.pace_trend??'—'],['Priority score',intel?`${intel.priority_score}/100`:'—']].map(([k,v])=><div className="data-detail" key={k}><span>{k}</span><strong>{v}</strong></div>)}</div></Panel></div>
 {intel&&<div className={`notice section-gap ${intel.risk==='HIGH'?'warning':''}`}><Info size={18}/><span><strong>{intel.risk} forecast risk.</strong> {intel.action}</span></div>}
 <Panel title="All screenings · predicted selling" className="section-gap"><Table><thead><tr><th>Screening</th><th>Observed</th><th>Next 7d</th><th>Next 14d</th><th>Final forecast</th><th>Occupancy</th><th>Risk</th><th>Priority</th></tr></thead><tbody>{d.screenings.map(r=>{const x=d.sales_intelligence.screenings.find(i=>i.screening_id===r.id);return <tr key={r.id}><td>{shortDate(r.date)}<small>{r.time??'Time TBC'}</small></td><td>{number(r.tickets_sold)} / {r.capacity}</td><td>{x?`+${number(x.expected_new_tickets_7d)}`:'—'}</td><td>{x?`+${number(x.expected_new_tickets_14d)}`:'—'}</td><td><strong>{number(x?.final_base)}</strong><small>{number(x?.final_low)}–{number(x?.final_high)}</small></td><td>{percent(x?.final_occupancy_pct)}</td><td><SourceBadge source={x?.risk??'UNKNOWN'}/></td><td>{x?`${x.priority_score}/100`:'—'}</td></tr>})}</tbody></Table></Panel>
 <div className="two-columns section-gap"><Panel title="Model evidence" aside={<SourceBadge source="MODEL ESTIMATE"/>}><p className="microcopy">{d.sales_intelligence.evidence.final_demand}</p><p className="microcopy section-gap">{d.sales_intelligence.evidence.near_term}</p><div className="notice section-gap"><Info size={17}/><span>{d.sales_intelligence.evidence.warning}</span></div></Panel><Panel title="Observation history"><Table><thead><tr><th>Observed</th><th>Tickets</th><th>Days before</th></tr></thead><tbody>{s.actual_curve.length?s.actual_curve.toReversed().map(p=><tr key={p.observed_at}><td>{new Date(p.observed_at).toLocaleString('en-GB',{timeZone:'Europe/Berlin'})}</td><td>{p.tickets}</td><td>{p.days}</td></tr>):<tr><td colSpan={3}>No Resolution ticket observations yet.</td></tr>}</tbody></Table><p className="microcopy section-gap">Save the cumulative count whenever new sales data is available. Three- and seven-day pace appear once a full observation window exists.</p></Panel></div></>;
}
