'use client';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import {ArrowUpRight,CalendarDays,MapPin,Radio,Ticket,Armchair,Wallet,Activity,Lightbulb} from 'lucide-react';
import {Button,Progress} from '@reef/ui';
import type {Dashboard} from '@reef/types';
import {useResource} from '@/lib/hooks';
import {money,number,shortDate,fullDate,weekday} from '@/lib/format';
import {PageTitle,Panel,Metric,Loading,ErrorState,StatusBadge,SourceBadge,TextLink} from '@/components/shared';
import {BookingChart} from '@/components/booking-chart';
import {SalesEntry} from '@/components/sales-entry';
const GeoMap=dynamic(()=>import('@/components/geo-map'),{ssr:false});
export default function DashboardPage(){
 const {data:d,error,loading,refresh}=useResource<Dashboard>('/dashboard');
 if(loading)return <Loading/>;if(error||!d)return <ErrorState message={error} retry={refresh}/>;
 return <><PageTitle eyebrow="RESOLUTION / FEBRUARY 2027" title="Ticket Sales Command Center" description={`${d.screenings.length} screenings at ESO Supernova · ${d.summary.capacity} seats · One clear next move`} action={<SalesEntry screenings={d.screenings} onSaved={refresh}/>}/>
 <section className="action-hero" aria-labelledby="today-heading"><div className="action-main"><div className="action-label"><Lightbulb size={18}/>WHAT SHOULD WE DO TODAY?</div><h2 id="today-heading">{d.today.headline}</h2><p>{d.today.action}</p><div className="action-meta"><div><Radio size={17}/><div><span>Channel</span><strong>{d.today.channel}</strong></div></div><div><MapPin size={17}/><div><span>Where</span><strong>{d.today.geography}</strong></div></div><div><CalendarDays size={17}/><div><span>Next review</span><strong>{fullDate(d.today.next_review)}</strong></div></div></div></div><aside className="action-aside"><span>Recommended commitment</span><strong>{money(d.summary.recommended_budget_cents)}</strong><p>{d.summary.recommended_budget_cents?`${money(d.today.daily_budget_cents)}/day for ${d.today.duration_days} days on the priority show.`:'The budget is a ceiling. There is no need to spend it.'}</p><Button asChild variant="outline"><Link href="/marketing">View action plan<ArrowUpRight size={16}/></Link></Button></aside></section>
 <div className="kpi-grid"><Metric label="Expected final tickets" value={number(d.sales_intelligence.portfolio.final_base)} detail={`${number(d.sales_intelligence.portfolio.final_low)}–${number(d.sales_intelligence.portfolio.final_high)} model range`} icon={<Ticket/>}/><Metric label="Expected occupancy" value={`${number(d.sales_intelligence.portfolio.final_occupancy_pct)}%`} detail={`${d.summary.capacity} total seats across ${d.screenings.length} screenings`} icon={<Armchair/>}/><Metric label="Expected new tickets · 7d" value={`+${number(d.sales_intelligence.portfolio.expected_new_tickets_7d)}`} detail={d.summary.observed_screenings?'Updates from observed booking pace':'Pre-sales trajectory until live observations arrive'} icon={<Activity/>}/><Metric label="Campaign ceiling" value={money(d.budget.ceiling_cents)} detail={`${money(d.budget.spent_cents)} recorded spend · ${money(d.budget.reserve_cents)} reserve`} icon={<Wallet/>}/></div>
 <div className="dashboard-row"><Panel title="Screening control" aside={<TextLink href="/ticket-sales">All screenings</TextLink>}><div className="screenings-grid">{d.screenings.map(s=><Link href={`/ticket-sales?screening=${s.id}`} key={s.id} className="screening-card"><div className="screening-date"><strong>{shortDate(s.date)}</strong><span>{weekday(s.date)}</span></div><StatusBadge status={s.decision.status}/><div className="screening-sold">{number(s.tickets_sold)}<span>/ {s.capacity}</span></div><Progress value={(s.tickets_sold??0)/s.capacity*100} label={`${shortDate(s.date)} tickets sold`}/><p>{s.tickets_sold===null?'No confirmed sales observation':`${number(s.seats_remaining)} seats remaining · target ${s.decision.target_today}`}</p><div className="screening-note"><strong>{s.forecast.base===null?'Forecast awaiting data':`${s.forecast.low}–${s.forecast.high} expected tickets`}</strong><p>{s.forecast.base===null?'Update sales to unlock a forecast.':`Base estimate: ${s.forecast.base} tickets`}</p></div><div className="screening-bottom"><span>{s.days_until} days to go</span><strong>{money(s.decision.recommended_budget_cents)}</strong></div></Link>)}</div><p className="chart-caption" style={{marginTop:15}}>Screening times and ticket-opening dates await ESO confirmation.</p></Panel>
 <Panel title="Healthy booking curve" aside={<SourceBadge source="PLANNING ASSUMPTION"/>}><BookingChart curve={d.curve}/><div className="legend"><span><i/>Management target</span><span>One screening · 109 seats</span></div><p className="chart-caption">Days before screening · Final target: {d.curve.find(p=>p.days===0)?.tickets} tickets</p></Panel></div>
 <div className="three-columns"><Panel title="Advertising operating plan" aside={<TextLink href="/marketing">View plan</TextLink>}><div className="plan-step"><span className="step-number">1</span><div><h3>Prepare the launch</h3><p>Confirm ESO booking links, tracking and creative.</p><span className="step-budget">Additional spend: €0</span></div></div><div className="plan-step"><span className="step-number">2</span><div><h3>Measure the organic baseline</h3><p>Record ticket sales. Review 48 hours after opening.</p><span className="step-budget">Healthy shows receive €0 extra</span></div></div><div className="plan-step"><span className="step-number">3</span><div><h3>Test only when a show needs help</h3><p>{money(d.rules.meta_test_cents)} Meta + {money(d.rules.google_test_cents)} Google. Review before scaling.</p><span className="step-budget">{fullDate(d.rules.paid_test_start)} · Planning assumption</span></div></div></Panel>
 <Panel title="Where to advertise" aside={<TextLink href="/geography">Predicted ranking</TextLink>}><GeoMap small lat={d.project.latitude} lon={d.project.longitude}/><div className="zone-mini-list"><div><strong>Dynamic geography ranking</strong><span>Campaign response can move a place above a closer zone.</span></div><div><strong>No invented conversion</strong><span>Without ticket attribution, distance is only a planning prior.</span></div><div><strong>Re-rank after every test</strong><span>Imported spend, clicks and ticket signals update the recommendation.</span></div></div></Panel>
 <Panel title="How much to spend" aside={<TextLink href="/marketing">Budget</TextLink>}>{(['META','GOOGLE'] as const).map(key=><div className="budget-line" key={key}><div className="budget-label"><div><span className="channel-mark">{key==='META'?'∞':'G'}</span><span>{key==='META'?'Meta / Instagram':'Google Search'}</span></div><strong>{money(d.budget.channels[key].ceiling_cents)}</strong></div><Progress value={(d.budget.channels[key].spent_cents+d.budget.channels[key].committed_cents)/Math.max(1,d.budget.channels[key].ceiling_cents)*100} label={`${key} budget used`}/></div>)}<div className="budget-label"><span>Tactical reserve</span><strong>{money(d.budget.reserve_cents)}</strong></div><div className="budget-foot">Spend is conditional on sales performance. <strong>Healthy screenings receive €0 extra.</strong></div></Panel></div>
 </>;
}
