'use client';
import {useState} from 'react';
import {Plus,Upload,Download,Info} from 'lucide-react';
import {Button,Dialog,DialogContent,DialogTitle,DialogDescription,Input,Label,Select,Textarea,Table} from '@reef/ui';
import type {Campaign,Creative,Dashboard,Geography} from '@reef/types';
import {api} from '@/lib/api';
import {useResource} from '@/lib/hooks';
import {money,number,percent,shortDate} from '@/lib/format';
import {PageTitle,Panel,Loading,ErrorState,Empty,SourceBadge,Feedback} from '@/components/shared';
import {useUser} from '@/components/shell';
interface ImportPreview {rows:{date:string;spend_cents:number;impressions:number;clicks:number;attributed_tickets:number|null}[];conflicts:string[];spend_cents:number}
export default function CampaignsPage(){
 const campaigns=useResource<Campaign[]>('/campaigns');const dashboard=useResource<Dashboard>('/dashboard');const creatives=useResource<Creative[]>('/creatives');const geographies=useResource<Geography[]>('/geography');const user=useUser();
 const [createOpen,setCreateOpen]=useState(false),[importing,setImporting]=useState<Campaign|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<ImportPreview|null>(null),[replace,setReplace]=useState(false),[platform,setPlatform]=useState('ALL');
 if(campaigns.loading||dashboard.loading||creatives.loading||geographies.loading)return <Loading/>;
 const loadError=campaigns.error||dashboard.error||creatives.error||geographies.error;
 if(loadError||!campaigns.data||!dashboard.data||!creatives.data||!geographies.data)return <ErrorState message={loadError} retry={()=>{void campaigns.refresh();void dashboard.refresh();void creatives.refresh();void geographies.refresh();}}/>;
 const d=dashboard.data;const editable=user?.role!=='viewer';
 async function upload(isPreview:boolean){if(!file||!importing)return;setBusy(true);setError('');const body=new FormData();body.append('file',file);body.append('campaign_id',importing.id);body.append('provider',importing.platform);body.append('preview',String(isPreview));body.append('replace',String(replace));try{if(isPreview)setPreview(await api<ImportPreview>('/imports/campaigns',{method:'POST',body}));else{await api('/imports/campaigns',{method:'POST',body});setImporting(null);setSuccess('Campaign observations imported. Sales attribution and budget reports are updated.');void campaigns.refresh();void dashboard.refresh();}}catch(e){setError(e instanceof Error?e.message:'Import failed');}finally{setBusy(false);}}
 return <><PageTitle eyebrow="CAMPAIGN MANAGER" title="Plan, measure, then decide" description="Keep each ad set linked to a screening, geography and creative." action={<Button disabled={!editable} onClick={()=>{setCreateOpen(true);setError('');}}><Plus size={16}/>New campaign</Button>}/>
 <div className="notice"><Info size={18}/><span>Campaigns here are planning and measurement records. Status changes do not launch or pause ads on Meta or Google. Manage delivery in the advertising platform.</span></div>
 <div className="toolbar"><Select aria-label="Filter by platform" value={platform} onChange={e=>setPlatform(e.target.value)}><option value="ALL">All platforms</option><option value="META">Meta</option><option value="GOOGLE">Google Search</option></Select><Button asChild variant="outline" size="sm"><a href="/campaign-import-template.csv" download><Download size={15}/>CSV template</a></Button></div><Feedback success={success} error={(!createOpen&&!importing)?error:''}/>
 <Panel title="Campaigns" aside={<span className="microcopy">{campaigns.data.length} records · {money(d.budget.committed_cents)} committed</span>}>{campaigns.data.length?<Table><thead><tr><th>Campaign / ad set</th><th>Screening / zone</th><th>Spend / budget</th><th>CTR</th><th>Landing views</th><th>Ticket signal</th><th>Status</th><th>Data</th></tr></thead><tbody>{campaigns.data.filter(c=>platform==='ALL'||c.platform===platform).map(c=><tr key={c.id}><td>{c.name}<small>{c.platform} · {c.ad_set||'Ad set not specified'}</small><small>{shortDate(c.start_date)}–{shortDate(c.end_date)}</small></td><td>{shortDate(c.screening_id.slice(-10))}<small>{c.geography_id.toUpperCase()} · {creatives.data?.find(x=>x.id===c.creative_id)?.concept??c.creative_id}</small></td><td>{money(c.metrics.spend_cents)}<small>Budget: {money(c.budget_cents)}</small></td><td>{percent(c.metrics.ctr)}</td><td>{number(c.metrics.landing_page_views)}</td><td>{number(c.metrics.attributed_tickets)}<small>{c.metrics.cost_per_ticket_cents===null?'No cost / ticket yet':`${money(c.metrics.cost_per_ticket_cents)} / ticket`}</small></td><td><Select aria-label={`Status for ${c.name}`} value={c.status} disabled={!editable||busy} onChange={async e=>{setBusy(true);setError('');try{await api(`/campaigns/${c.id}/status`,{method:'PATCH',body:JSON.stringify({status:e.target.value})});setSuccess('Planning status saved. No advertising platform was changed.');void campaigns.refresh();void dashboard.refresh();}catch(err){setError(err instanceof Error?err.message:'Could not update status');}finally{setBusy(false);}}} style={{height:34,minWidth:120,fontSize:12}}>{['DRAFT','PLANNED','ACTIVE','PAUSED','COMPLETED','CANCELLED'].map(s=><option key={s} disabled={s==='DRAFT'}>{s}</option>)}</Select></td><td><Button size="sm" variant="outline" disabled={!editable} onClick={()=>{setImporting(c);setFile(null);setPreview(null);setReplace(false);setError('');}}><Upload size={13}/>Import CSV</Button></td></tr>)}</tbody></Table>:<Empty title="Ready for your first campaign" detail="Create a draft when you have an ad set to plan or measure. No spend is committed until the backend checks the sales and budget rules." action={<Button variant="outline" disabled={!editable} onClick={()=>setCreateOpen(true)}><Plus size={15}/>Create campaign draft</Button>}/>}</Panel>
 <div className="two-columns section-gap"><Panel title="Initial test, when justified"><div className="data-detail"><span>Meta local test</span><strong>{money(d.rules.meta_test_cents)}</strong></div><div className="data-detail"><span>Google Search test</span><strong>{money(d.rules.google_test_cents)}</strong></div><p className="microcopy section-gap">Create separate ad-set records for each zone and creative. Allocate the test across those records; the channel totals remain a ceiling. Healthy screenings receive €0 extra.</p></Panel><Panel title="CSV import requirements"><p className="microcopy">Use a daily export for one ad set, creative and zone. Required: date, EUR spend, impressions and clicks. Landing views and attributed tickets can be blank. Generic Google conversions are not automatically treated as ticket sales.</p><p className="microcopy section-gap">Preview before saving. Identical imports are idempotent; changed dates require explicit replacement. A platform ticket signal is not proven incremental lift.</p></Panel></div>
 <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent><DialogTitle>New campaign draft</DialogTitle><DialogDescription className="dialog-description">One record per platform, ad set, creative and geography. Drafts do not commit budget.</DialogDescription><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);const payload:Record<string,unknown>={...Object.fromEntries(f.entries()),budget_cents:Math.round(Number(f.get('budget_eur'))*100)};delete payload.budget_eur;try{await api('/campaigns',{method:'POST',body:JSON.stringify(payload)});setCreateOpen(false);setSuccess('Draft created. Review its budget before marking it planned.');void campaigns.refresh();}catch(err){setError(err instanceof Error?err.message:'Unable to create draft');}finally{setBusy(false);}}}>
 <div className="field"><Label htmlFor="campaign-name">Campaign name</Label><Input id="campaign-name" name="name" required placeholder="Resolution · 02 Feb · local event test"/></div><div className="form-grid"><div className="field"><Label htmlFor="platform">Platform</Label><Select id="platform" name="platform"><option value="META">Meta</option><option value="GOOGLE">Google Search</option></Select></div><div className="field"><Label htmlFor="campaign-screening">Associated screening</Label><Select id="campaign-screening" name="screening_id">{d.screenings.map(s=><option key={s.id} value={s.id}>{shortDate(s.date)} 2027</option>)}</Select></div><div className="field"><Label htmlFor="ad-set">Ad set / group</Label><Input id="ad-set" name="ad_set" placeholder="Garching · Event · Adults 20–60"/></div><div className="field"><Label htmlFor="campaign-zone">Geography</Label><Select id="campaign-zone" name="geography_id">{geographies.data.map(z=><option key={z.id} value={z.id}>{z.name}</option>)}</Select></div><div className="field"><Label htmlFor="campaign-creative">Creative</Label><Select id="campaign-creative" name="creative_id" defaultValue="creative-b">{creatives.data.filter(c=>c.status!=='RETIRED').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></div><div className="field"><Label htmlFor="campaign-budget">Budget ceiling (€)</Label><Input id="campaign-budget" name="budget_eur" type="number" min="0" max="500" step="0.01" defaultValue="70" required/></div><div className="field"><Label htmlFor="campaign-start">Start date</Label><Input id="campaign-start" name="start_date" type="date" defaultValue={d.rules.paid_test_start} required/></div><div className="field"><Label htmlFor="campaign-end">End date</Label><Input id="campaign-end" name="end_date" type="date" defaultValue={d.rules.paid_test_end} required/></div></div><div className="field"><Label htmlFor="audience">Audience</Label><Input id="audience" name="audience" defaultValue="Adults 20–60 · local culture and music" required/></div><Feedback error={error}/><div className="form-actions"><Button type="submit" disabled={busy}>{busy?'Saving…':'Save campaign draft'}</Button></div></form></DialogContent></Dialog>
 <Dialog open={!!importing} onOpenChange={o=>{if(!o)setImporting(null);}}><DialogContent><DialogTitle>Import campaign observations</DialogTitle><DialogDescription className="dialog-description">{importing?.name} · Upload UTF-8 CSV with a daily EUR breakdown. Maximum 2 MB.</DialogDescription><div className="field"><Label htmlFor="csv-file">Meta / Google / normalized CSV</Label><Input id="csv-file" type="file" accept=".csv,text/csv" onChange={e=>{setFile(e.target.files?.[0]??null);setPreview(null);setError('');}}/></div>{preview&&<><div className="notice">{preview.rows.length} daily rows · {money(preview.spend_cents)} total observed spend</div><Table><thead><tr><th>Date</th><th>Spend</th><th>Clicks</th><th>Tickets</th></tr></thead><tbody>{preview.rows.slice(0,8).map(r=><tr key={r.date}><td>{r.date}</td><td>{money(r.spend_cents)}</td><td>{r.clicks}</td><td>{number(r.attributed_tickets)}</td></tr>)}</tbody></Table>{preview.conflicts.length>0&&<label className="checkbox-label section-gap"><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/>Replace {preview.conflicts.length} changed daily observations</label>}</>}<Feedback error={error}/><div className="form-actions"><Button variant="outline" disabled={!file||busy} onClick={()=>upload(true)}>{busy?'Working…':'Preview import'}</Button>{preview&&<Button disabled={busy||(preview.conflicts.length>0&&!replace)} onClick={()=>upload(false)}>Save {preview.rows.length} observations</Button>}</div></DialogContent></Dialog></>;
}
