'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {ArrowRight,ShieldCheck,Info,CalendarDays,Target,Wallet,RefreshCw,MapPin,Activity} from 'lucide-react';
import {Button,Input,Progress,Table} from '@reef/ui';
import type {Dashboard,ScenarioResult} from '@reef/types';
import {useResource} from '@/lib/hooks';
import {api} from '@/lib/api';
import {money,shortDate,number} from '@/lib/format';
import {PageTitle,Panel,Loading,ErrorState,Metric,SourceBadge} from '@/components/shared';
export default function MarketingPage(){
 const {data:d,error,loading,refresh}=useResource<Dashboard>('/dashboard');const [budget,setBudget]=useState('100');const [scenario,setScenario]=useState<ScenarioResult|null>(null);const [busy,setBusy]=useState(false);const [scenarioError,setScenarioError]=useState('');
 async function analyze(){if(!d)return;setBusy(true);setScenarioError('');try{setScenario(await api<ScenarioResult>('/scenarios',{method:'POST',body:JSON.stringify({advertising_budget_cents:Math.max(0,Math.round(Number(budget||0)*100)),ad_incremental_cpa_cents:d.rules.ad_incremental_cpa_cents})}));}catch(e){setScenarioError(e instanceof Error?e.message:'Unable to build marketing intelligence');}finally{setBusy(false)}}
 useEffect(()=>{if(d&&!scenario&&!busy)void analyze();},[d]);
 if(loading)return <Loading/>;if(error||!d)return <ErrorState message={error} retry={refresh}/>;const plan=scenario?.marketing_plan;const target=plan?.target_screening;const geo=plan?.top_geography;const channel=plan?.top_channel;
 return <><PageTitle eyebrow="MARKETING INTELLIGENCE" title="Decide where, when and how to test" description="Marketing recommendations now react to forecast shortfall, geography evidence and imported campaign response instead of relying on a fixed place." action={<Button asChild><Link href="/campaigns">Manage campaigns<ArrowRight size={16}/></Link></Button>}/>
 <div className="toolbar"><div className="inline-actions"><label className="microcopy" htmlFor="marketing-budget">Scenario budget €</label><Input id="marketing-budget" type="number" min="0" step="10" value={budget} onChange={e=>setBudget(e.target.value)} style={{width:120}}/><Button onClick={analyze} disabled={busy} variant="outline"><RefreshCw size={16}/>{busy?'Analysing…':'Build allocation'}</Button></div><span className="microcopy">This is a planning scenario; it does not commit campaign spend.</span></div>
 {scenarioError&&<div className="notice warning"><Info size={18}/><span>{scenarioError}</span></div>}
 {plan&&<div className="action-hero"><div className="action-main"><div className="eyebrow">WHAT REEF SHOULD TEST NEXT</div><h2>{plan.recommendation}</h2><p>{target?`${shortDate(target.date)} has a ${target.risk.toLowerCase()} forecast risk and priority score ${target.priority_score}/100.`:'Collect more evidence before scaling.'}</p><div className="action-meta"><div><span>Screening</span><strong>{target?shortDate(target.date):'—'}</strong></div><div><span>Place</span><strong>{geo?.name??'—'}</strong></div><div><span>Channel</span><strong>{channel?.platform??'Test needed'}</strong></div><div><span>Scenario budget</span><strong>{money(plan.advertising_budget_cents)}</strong></div></div></div><div className="action-aside"><MapPin size={21}/><span>Top geography score</span><strong>{geo?number(geo.score):'—'}</strong><p>{geo?`${geo.classification} · ${geo.confidence} confidence`:'No ranking yet'}</p></div></div>}
 <div className={`notice ${d.budget.over_ceiling?'warning':''}`}><ShieldCheck size={19}/><span>{d.budget.over_ceiling?'Recorded spend or commitments exceed a channel ceiling. Stop additional commitments and review the budget.':`Operational ceiling remains separate from analysis. ${money(d.budget.reserve_cents)} stays protected.`}</span></div>
 <div className="kpi-grid"><Metric label="Expected final tickets" value={number(scenario?.portfolio.tickets_base??d.sales_intelligence.portfolio.final_base)} detail={`${number(scenario?.portfolio.tickets_low??d.sales_intelligence.portfolio.final_low)}–${number(scenario?.portfolio.tickets_high??d.sales_intelligence.portfolio.final_high)} range`} icon={<Target/>}/><Metric label="Expected new tickets · 7d" value={`+${number(d.sales_intelligence.portfolio.expected_new_tickets_7d)}`} detail="Across all screenings" icon={<Activity/>}/><Metric label="Recorded ad spend" value={money(d.budget.spent_cents)} detail="Imported campaign observations" icon={<Wallet/>}/><Metric label="Available operational budget" value={money(d.budget.available_cents)} detail="Excludes commitments and protected reserve" icon={<ShieldCheck/>}/></div>
 {plan&&<div className="split-layout"><Panel title="Which screening needs the budget?" aside={<SourceBadge source="MODEL ESTIMATE"/>}><Table><thead><tr><th>Screening</th><th>Risk</th><th>Priority</th><th>Forecast gap</th><th>Suggested budget</th><th>Expected ad tickets</th></tr></thead><tbody>{plan.screenings.map(s=><tr key={s.screening_id}><td>{shortDate(s.date)}</td><td><SourceBadge source={s.risk}/></td><td>{s.priority_score}/100</td><td>{number(s.forecast_shortfall)}</td><td>{money(s.recommended_budget_cents)}</td><td>{number(s.expected_incremental_tickets)}</td></tr>)}</tbody></Table></Panel>
 <Panel title="Where should we advertise?" aside={<SourceBadge source={plan.classification}/>}><Table><thead><tr><th>Rank</th><th>Place</th><th>Score</th><th>Share</th><th>Budget</th></tr></thead><tbody>{plan.geographies.map(g=><tr key={g.id}><td>#{g.rank}</td><td>{g.name}<small>{g.classification}</small></td><td>{number(g.score)}/100</td><td>{number(g.recommended_share_pct)}%</td><td>{money(g.recommended_budget_cents)}</td></tr>)}</tbody></Table><p className="microcopy section-gap">The place ranking changes when imported campaign evidence changes. Distance is only the fallback travel-friction prior.</p></Panel></div>}
 {plan&&<div className="two-columns section-gap"><Panel title="Channel evidence"><Table><thead><tr><th>Channel</th><th>Evidence</th><th>Budget share</th><th>Observed CPA</th></tr></thead><tbody>{plan.channels.map(c=><tr key={c.platform}><td>{c.platform==='META'?'Meta / Instagram / Facebook':'Google Search'}</td><td><SourceBadge source={c.classification}/><small>{c.basis}</small></td><td>{number(c.recommended_share_pct)}% · {money(c.recommended_budget_cents)}</td><td>{money(c.performance.cost_per_ticket_cents)}</td></tr>)}</tbody></Table></Panel>
 <Panel title="Audience signals"><Table><thead><tr><th>Audience</th><th>Evidence</th><th>Ticket signal</th></tr></thead><tbody>{plan.audiences.slice(0,5).map(a=><tr key={a.segment}><td>{a.segment}<small>{a.age??a.message??''}</small></td><td><SourceBadge source={a.classification}/><small>{a.basis}</small></td><td>{number(a.performance?.attributed_tickets)}</td></tr>)}</tbody></Table></Panel></div>}
 <div className="two-columns section-gap"><Panel title="Operational budget ceilings"><div className="stack">{(['META','GOOGLE'] as const).map(k=><div key={k}><div className="budget-label"><span>{k==='META'?'Meta / Instagram / Facebook':'Google Search'}</span><strong>{money(d.budget.channels[k].ceiling_cents)}</strong></div><Progress value={(d.budget.channels[k].spent_cents+d.budget.channels[k].committed_cents)/Math.max(1,d.budget.channels[k].ceiling_cents)*100} label={`${k} allocated budget`}/><p className="microcopy" style={{marginTop:8}}>{money(d.budget.channels[k].spent_cents)} spent · {money(d.budget.channels[k].committed_cents)} committed</p></div>)}</div></Panel><Panel title="Evidence rules"><div className="stack"><div className="notice"><Info size={17}/><span>Attributed tickets can improve ranking but do not prove incremental lift.</span></div><div className="notice"><Info size={17}/><span>If planning CPA is unknown, the app can rank places and allocate test budget but will not invent extra ticket sales.</span></div><div className="notice"><CalendarDays size={17}/><span>Re-run the allocation after each meaningful sales or campaign-data update.</span></div></div></Panel></div>
 {plan?.warnings?.length?<Panel title="Current limitations" className="section-gap"><ul className="scenario-warning-list">{plan.warnings.map(w=><li key={w}>{w}</li>)}</ul></Panel>:null}</>;
}
