'use client';
import Link from 'next/link';
import {ArrowRight,ShieldCheck,Info,CalendarDays,Target,Wallet,Check} from 'lucide-react';
import {Button,Progress,Table} from '@reef/ui';
import type {Dashboard} from '@reef/types';
import {useResource} from '@/lib/hooks';
import {money,shortDate,fullDate} from '@/lib/format';
import {PageTitle,Panel,Loading,ErrorState,Metric,SourceBadge,StatusBadge} from '@/components/shared';
export default function MarketingPage(){
 const {data:d,error,loading,refresh}=useResource<Dashboard>('/dashboard');if(loading)return <Loading/>;if(error||!d)return <ErrorState message={error} retry={refresh}/>;
 return <><PageTitle eyebrow="MARKETING PLANNER" title="Put the money where it is needed" description="Start with the sales gap. Spend only when a screening needs support." action={<Button asChild><Link href="/campaigns">Manage campaigns<ArrowRight size={16}/></Link></Button>}/>
 <div className={`notice ${d.budget.over_ceiling?'warning':''}`}><ShieldCheck size={19}/><span>{d.budget.over_ceiling?'Recorded spend or commitments exceed a channel ceiling. Stop additional commitments and review the budget.':`Healthy screenings get €0 additional spend. ${money(d.budget.reserve_cents)} stays protected until management changes the allocation.`}</span></div>
 <div className="kpi-grid"><Metric label="Total ceiling" value={money(d.budget.ceiling_cents)} detail="Maximum available for this launch" icon={<Wallet/>}/><Metric label="Recorded spend" value={money(d.budget.spent_cents)} detail="From imported campaign observations" icon={<Target/>}/><Metric label="Committed, not spent" value={money(d.budget.committed_cents)} detail="Planned / active campaign balances" icon={<CalendarDays/>}/><Metric label="Available to allocate" value={money(d.budget.available_cents)} detail="Excludes commitments and protected reserve" icon={<ShieldCheck/>}/></div>
 <div className="split-layout"><Panel title="Screening-by-screening action plan" aside={<SourceBadge source="ESTIMATED"/>}><Table><thead><tr><th>Screening</th><th>Position</th><th>Recommended action</th><th>Commitment</th><th>Review</th></tr></thead><tbody>{d.screenings.map(s=><tr key={s.id}><td>{shortDate(s.date)}<small>{s.days_until} days away</small></td><td><StatusBadge status={s.decision.status}/></td><td className="wrap">{s.decision.action}<small>{s.decision.channel} · {s.decision.geography}</small></td><td>{money(s.decision.recommended_budget_cents)}<small>{money(s.decision.daily_budget_cents)}/day</small></td><td>{shortDate(s.decision.next_review)}</td></tr>)}</tbody></Table></Panel>
 <Panel title="Allocation ceilings"><div className="stack">{(['META','GOOGLE'] as const).map(k=><div key={k}><div className="budget-label"><span>{k==='META'?'Meta / Instagram / Facebook':'Google Search'}</span><strong>{money(d.budget.channels[k].ceiling_cents)}</strong></div><Progress value={(d.budget.channels[k].spent_cents+d.budget.channels[k].committed_cents)/Math.max(1,d.budget.channels[k].ceiling_cents)*100} label={`${k} allocated budget`}/><p className="microcopy" style={{marginTop:8}}>{money(d.budget.channels[k].spent_cents)} spent · {money(d.budget.channels[k].committed_cents)} committed</p></div>)}<div className="budget-label"><span>Tactical reserve</span><strong>{money(d.budget.reserve_cents)}</strong></div></div><div className="budget-foot section-gap">Unused budget is a good outcome when ticket sales stay healthy.</div></Panel></div>
 <div className="two-columns section-gap"><Panel title="The launch sequence" aside={<SourceBadge source="PLANNING ASSUMPTION"/>}>{[
 ['Prepare booking and tracking',`Before ${fullDate(d.rules.sales_open_target)}. Confirm all four ESO links, screening times, ticket reporting and creative copy.`,'€0'],
 ['Observe without paid advertising','Record an organic baseline. Review 48 hours after confirmed ticket opening.','€0'],
 ['Run a controlled initial test',`${fullDate(d.rules.paid_test_start)}–${shortDate(d.rules.paid_test_end)}. Only activate for a behind-target show with current sales data.`,`${money(d.rules.meta_test_cents)} Meta + ${money(d.rules.google_test_cents)} Google`],
 ['Scale conditionally',`Review after ${d.rules.campaign_days} days. Keep Zone A and B first. Stop the show at ${d.rules.near_full_tickets} tickets and reassess the next screening.`,'Within remaining ceilings']
 ].map(([title,body,spend],i)=><div className="plan-step" key={title}><span className="step-number">{i+1}</span><div><h3>{title}</h3><p>{body}</p><span className="step-budget">{spend}</span></div></div>)}</Panel>
 <Panel title="Management rules"><Table><thead><tr><th>Position</th><th>Trigger</th><th>Response</th></tr></thead><tbody><tr><td><StatusBadge status="ON_TRACK"/></td><td>At / above target</td><td>€0 extra</td></tr><tr><td><StatusBadge status="WATCH"/></td><td>{Math.round(d.rules.watch_ratio*100)}–99% of target</td><td>{money(d.rules.watch_daily_cents)}/day · {d.rules.campaign_days} days</td></tr><tr><td><StatusBadge status="ACTION"/></td><td>Below {Math.round(d.rules.watch_ratio*100)}%</td><td>{money(d.rules.action_daily_cents)}/day recovery</td></tr><tr><td><StatusBadge status="NEAR_FULL"/></td><td>{d.rules.near_full_tickets}+ tickets</td><td>Stop and promote next screening</td></tr></tbody></Table><p className="microcopy section-gap">Missing or older-than-{d.rules.stale_after_hours}-hour sales observations suspend paid recommendations. Rules are maintained in Settings and applied by the API.</p></Panel></div></>;
}
