'use client';
import {useState} from 'react';
import {FileChartColumn,Ticket,Megaphone,Wallet,ClipboardCheck,Lightbulb,Download,Printer} from 'lucide-react';
import {Button,Card,Table} from '@reef/ui';
import type {Report} from '@reef/types';
import {useResource} from '@/lib/hooks';
import {fullDate} from '@/lib/format';
import {PageTitle,Loading,ErrorState,Empty,SourceBadge} from '@/components/shared';
const choices=[['daily','Daily ticket report',Ticket],['campaigns','Campaign performance',Megaphone],['screenings','Screening performance',FileChartColumn],['budget','Budget report',Wallet],['post-event','Post-event report',ClipboardCheck],['learnings','Marketing learnings',Lightbulb]] as const;
export default function ReportsPage(){const [kind,setKind]=useState('daily');return <><PageTitle eyebrow="MANAGEMENT REPORTS" title="The numbers. The decision. The next step." description="A current view of ticket sales and campaign performance, ready to share."/><div className="report-choice-grid">{choices.map(([key,title,Icon])=><button key={key} className="report-choice" aria-pressed={kind===key} onClick={()=>setKind(key)}><Icon size={23}/>{title}</button>)}</div><ReportView kind={kind}/></>;}
function ReportView({kind}:{kind:string}){const {data:r,error,loading,refresh}=useResource<Report>(`/reports/${kind}`);if(loading)return <Loading/>;if(error||!r)return <ErrorState message={error} retry={refresh}/>;const cols=Object.keys(r.rows[0]??{});return <><div className="toolbar"><SourceBadge source="OBSERVATIONS + LABELED ESTIMATES"/><div className="inline-actions"><Button asChild variant="outline"><a href={`/api/v1/reports/${kind}?format=csv`} download><Download size={16}/>Export CSV</a></Button><Button variant="outline" onClick={()=>window.print()}><Printer size={16}/>Print / Save PDF</Button></div></div><Card className="report-document"><div className="report-brand"><div><div className="eyebrow">REEF LAUNCH INTELLIGENCE / MANAGEMENT REPORT</div><h2>{r.title}</h2><p className="microcopy">{r.project.name} · {fullDate(r.generated_at)}</p></div><strong>REEF</strong></div><div className="report-recommendation"><div className="eyebrow" style={{marginBottom:6}}>TODAY’S RECOMMENDATION</div>{r.recommendation}</div>{r.rows.length?<Table><thead><tr>{cols.map(k=><th key={k}>{k.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{r.rows.map((row,i)=><tr key={i}>{cols.map(k=><td key={k}>{row[k]===null?'—':typeof row[k]==='number'?new Intl.NumberFormat('en-GB',{maximumFractionDigits:2}).format(row[k] as number):String(row[k])}</td>)}</tr>)}</tbody></Table>:<Empty title="No campaign observations yet" detail="Import the first daily campaign export to build this report. No performance values have been invented."/>}<ul className="report-notes">{r.notes.map(n=><li key={n}>{n}</li>)}</ul><p className="microcopy section-gap">Prepared {new Date(r.generated_at).toLocaleString('en-GB',{timeZone:'Europe/Berlin'})} Europe/Berlin · Unknown values are shown as —.</p></Card></>;}
