'use client';
import {useState} from 'react';
import {Plus,Pencil,ExternalLink,Info} from 'lucide-react';
import {Button,Dialog,DialogContent,DialogTitle,DialogDescription,Input,Label,Textarea,Select} from '@reef/ui';
import type {Creative} from '@reef/types';
import {useResource} from '@/lib/hooks';
import {api} from '@/lib/api';
import {money,number,percent} from '@/lib/format';
import {PageTitle,Panel,Loading,ErrorState,SourceBadge,Feedback} from '@/components/shared';
import {useUser} from '@/components/shell';
export default function CreativesPage(){
 const {data,error,loading,refresh}=useResource<Creative[]>('/creatives');const user=useUser();const [editing,setEditing]=useState<Creative|null>(null),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[saveError,setSaveError]=useState('');
 if(loading)return <Loading/>;if(error||!data)return <ErrorState message={error} retry={refresh}/>;
 function edit(c:Creative|null){setEditing(c);setSaveError('');setOpen(true);}
 return <><PageTitle eyebrow="CREATIVE INTELLIGENCE" title="Two ideas. One ticket decision." description="Compare the experience promise with a clear event and booking message." action={<Button disabled={user?.role==='viewer'} onClick={()=>edit(null)}><Plus size={16}/>New creative</Button>}/>
 <div className="notice"><Info size={18}/><span>Creative B is the initial event-focused test choice. No winning creative is claimed until ticket response is measured.</span></div>
 <div className="two-columns">{data.map(c=><Panel title={c.name} key={c.id} aside={<Button variant="ghost" size="sm" disabled={user?.role==='viewer'} onClick={()=>edit(c)}><Pencil size={14}/>Edit</Button>}><div className={`creative-preview ${c.concept.toLowerCase()==='event'?'event':''}`}><span className="creative-kicker">RESOLUTION / {c.concept.toUpperCase()}</span><h3>{c.headline}</h3><small>REEF DISTRIBUTION · ESO SUPERNOVA</small></div><p className="creative-copy">{c.body}</p><div className="inline-actions"><SourceBadge source={c.status}/><span className="microcopy">Copy concept · artwork not yet attached</span>{c.asset_url&&<a className="text-link right" href={c.asset_url} target="_blank" rel="noreferrer">View asset<ExternalLink size={14}/></a>}</div><div className="creative-metrics section-gap"><div><small>CTR</small><strong>{percent(c.performance.ctr)}</strong></div><div><small>Landing response</small><strong>{percent(c.performance.landing_page_response)}</strong></div><div><small>Ticket signal</small><strong>{number(c.performance.attributed_tickets)}</strong></div><div><small>Spend</small><strong>{money(c.performance.spend_cents)}</strong></div></div><p className="microcopy section-gap">{c.performance.observations?`${c.performance.observations} imported daily observations`:'No campaign observations yet. Connect this creative to an ad set and import its results.'}</p></Panel>)}</div>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogTitle>{editing?'Edit creative':'New creative'}</DialogTitle><DialogDescription className="dialog-description">Keep the promise specific. Use the confirmed screening date and ESO ticket link in final ads.</DialogDescription><form key={editing?.id??'new'} onSubmit={async e=>{e.preventDefault();setBusy(true);setSaveError('');const f=new FormData(e.currentTarget);const payload={name:f.get('name'),concept:f.get('concept'),headline:f.get('headline'),body:f.get('body'),status:f.get('status'),asset_url:f.get('asset_url')||null};try{await api(editing?`/creatives/${editing.id}`:'/creatives',{method:editing?'PUT':'POST',body:JSON.stringify(payload)});setOpen(false);void refresh();}catch(err){setSaveError(err instanceof Error?err.message:'Unable to save');}finally{setBusy(false);}}}>
 <div className="form-grid"><div className="field"><Label htmlFor="creative-name">Name</Label><Input name="name" id="creative-name" defaultValue={editing?.name} required/></div><div className="field"><Label htmlFor="creative-concept">Concept</Label><Input name="concept" id="creative-concept" defaultValue={editing?.concept??'Event'} required/></div></div><div className="field"><Label htmlFor="creative-headline">Headline</Label><Input id="creative-headline" name="headline" defaultValue={editing?.headline} required/></div><div className="field"><Label htmlFor="creative-body">Body copy</Label><Textarea name="body" id="creative-body" defaultValue={editing?.body} required/></div><div className="field"><Label htmlFor="asset-url">Artwork URL (optional)</Label><Input id="asset-url" name="asset_url" type="url" defaultValue={editing?.asset_url??''} placeholder="https://…"/></div><div className="field"><Label htmlFor="creative-status">Status</Label><Select id="creative-status" name="status" defaultValue={editing?.status??'DRAFT'}><option>DRAFT</option><option>READY</option><option>RETIRED</option></Select></div><Feedback error={saveError}/><div className="form-actions"><Button type="submit" disabled={busy}>{busy?'Saving…':'Save creative'}</Button></div></form></DialogContent></Dialog></>;
}
