'use client';
import dynamic from 'next/dynamic';
import {useEffect,useState} from 'react';
import {Info,MapPin,RefreshCw,Target} from 'lucide-react';
import {Button,Input,Select,Table} from '@reef/ui';
import type {Dashboard,Geography,ScenarioResult} from '@reef/types';
import {useResource} from '@/lib/hooks';
import {api} from '@/lib/api';
import {money,number} from '@/lib/format';
import {PageTitle,Panel,Loading,ErrorState,SourceBadge,Metric} from '@/components/shared';
const GeoMap=dynamic(()=>import('@/components/geo-map'),{ssr:false});
export default function GeographyPage(){
 const {data:d,error,loading,refresh}=useResource<Dashboard>('/dashboard');const geo=useResource<Geography[]>('/geography');const [zone,setZone]=useState('all');const [budget,setBudget]=useState('100');const [scenario,setScenario]=useState<ScenarioResult|null>(null);const [busy,setBusy]=useState(false);const [scenarioError,setScenarioError]=useState('');
 async function analyze(){if(!d)return;setBusy(true);setScenarioError('');try{setScenario(await api<ScenarioResult>('/scenarios',{method:'POST',body:JSON.stringify({advertising_budget_cents:Math.max(0,Math.round(Number(budget||0)*100)),ad_incremental_cpa_cents:d.rules.ad_incremental_cpa_cents})}));}catch(e){setScenarioError(e instanceof Error?e.message:'Unable to rank geographies');}finally{setBusy(false)}}
 useEffect(()=>{if(d&&!scenario&&!busy)void analyze();},[d]);
 if(loading||geo.loading)return <Loading/>;if(error||geo.error||!d||!geo.data)return <ErrorState message={error||geo.error} retry={()=>{void refresh();void geo.refresh();}}/>;const plan=scenario?.marketing_plan;const top=plan?.top_geography;
 return <><PageTitle eyebrow="GEOGRAPHIC INTELLIGENCE" title="Rank places by evidence, not a fixed zone list" description="The candidate catchment stays editable, but ranking and budget share now react to campaign performance and travel-friction evidence." action={<Button onClick={analyze} disabled={busy}><RefreshCw size={16}/>{busy?'Ranking…':'Re-run ranking'}</Button>}/>
 <div className="toolbar"><div className="inline-actions"><MapPin size={18}/><span className="microcopy">ESO Supernova · Garching bei München</span></div><div className="inline-actions"><label className="microcopy" htmlFor="geo-budget">Planning budget €</label><Input id="geo-budget" type="number" min="0" step="10" value={budget} onChange={e=>setBudget(e.target.value)} style={{width:110}}/><Select aria-label="Advertising zone" value={zone} onChange={e=>setZone(e.target.value)}><option value="all">All candidate zones</option>{geo.data.map(z=><option key={z.id} value={z.id}>{z.name}</option>)}</Select></div></div>
 {scenarioError&&<div className="notice warning"><Info size={18}/><span>{scenarioError}</span></div>}
 {plan&&<div className="kpi-grid"><Metric label="Top geography now" value={top?.name??'—'} detail={top?`Dynamic score ${number(top.score)}/100 · ${top.confidence} confidence`:'No ranking'} icon={<MapPin/>}/><Metric label="Suggested share" value={top?`${number(top.recommended_share_pct)}%`:'—'} detail={top?money(top.recommended_budget_cents):'Run a scenario'} icon={<Target/>}/><Metric label="Expected ad tickets" value={number(top?.expected_incremental_tickets)} detail={top?.expected_incremental_tickets==null?'Unavailable until ad response is estimated':'Scenario allocation, not causal proof'} icon={<Target/>}/><Metric label="Evidence mode" value={plan.classification} detail="Ranking upgrades automatically when campaign evidence is imported" icon={<Info/>}/></div>}
 <div className="split-layout"><Panel title="ESO candidate catchment" aside={<SourceBadge source={plan?.classification??'PLANNING ASSUMPTION'}/>}><GeoMap lat={d.project.latitude} lon={d.project.longitude} zone={zone}/><p className="microcopy section-gap">Radii are candidate markets, not fixed recommendations. The ranking on the right changes when observed campaign response changes. Straight-line distance is only a travel-friction prior.</p></Panel><div>{(plan?.geographies??geo.data.map((g,i)=>({id:g.id,name:g.name,min_km:g.min_km,max_km:g.max_km,rank:i+1,score:0,classification:'PLANNING ASSUMPTION',confidence:'LOW',recommended_share_pct:0,recommended_budget_cents:0,expected_incremental_tickets:null,performance:g.performance,basis:[g.notes]} as any))).map((g:any)=><section className="card zone-card" key={g.id} style={{borderLeftColor:g.rank===1?'#007f80':g.rank===2?'#34abb4':'#81c8d4'}}><h3><span className="geo-rank">#{g.rank}</span>{g.name}<span className="microcopy">{g.min_km}–{g.max_km} km</span></h3><div className="inline-actions"><SourceBadge source={g.classification}/><span className="microcopy">Score {number(g.score)}/100 · {g.confidence}</span></div><p>{g.basis?.[0]}</p><div className="zone-metrics"><div><small>Suggested budget</small><strong>{money(g.recommended_budget_cents)}</strong></div><div><small>Budget share</small><strong>{number(g.recommended_share_pct)}%</strong></div><div><small>Expected ad tickets</small><strong>{number(g.expected_incremental_tickets)}</strong></div></div></section>)}</div></div>
 {plan&&<Panel title="Why this ranking?" className="section-gap"><Table><thead><tr><th>Rank</th><th>Place</th><th>Decision score</th><th>Observed spend</th><th>Attributed tickets</th><th>Observed CPA</th><th>Evidence</th></tr></thead><tbody>{plan.geographies.map(g=><tr key={g.id}><td>#{g.rank}</td><td>{g.name}</td><td>{number(g.score)}/100</td><td>{money(g.performance.spend_cents)}</td><td>{number(g.performance.attributed_tickets)}</td><td>{money(g.performance.cost_per_ticket_cents)}</td><td><SourceBadge source={g.classification}/></td></tr>)}</tbody></Table></Panel>}
 <div className="notice section-gap"><Info size={18}/><span>Geography score is a decision ranking, not a probability of purchase. Attributed tickets can improve the ranking but are not proof that advertising caused the sale. {plan?.warnings?.[0]}</span></div></>;
}
