[browser]
gatherUsageStats = false

[server]
headless = true

[theme]
base = "light"
primaryColor = "#087E83"
backgroundColor = "#F7F9FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#14283D"
font = "sans serif"
