[browser]
gatherUsageStats = false

[server]
headless = true

[theme]
base = "light"
primaryColor = "#087E83"
backgroundColor = "#F6F9FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#102A43"
font = "sans serif"
